# Generated by Django 4.1 on 2024-11-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fear", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="champions",
            name="champion_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
